aws:
  s3:
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    clientId: ${AWS_CLIENT_ID}
    region: ${REGION:eu-north-1}
    bucketName: spheradevstack-s3bucket-1jlk0k9cw1kry
    defaultProfileImage: 6178abb3-7f12-9960-36b3-d49d025ebfa7.png

calendar:
  url-expiration-time: 1