package com.baidarka.booking.infrastructure.model;

public enum NotificationType {
    ADVERTISEMENT_BOOKED,
    ADVERTISEMENT_ORDERED,
    ADVERTISEMENT_LIKED,
    ADVERTISEMENT_CREATED,
    ADVERTISEMENT_VERIFIED,
    ADVERTISEMENT_DECLINED,
    ADVERTISEMENT_STOPPED,
    PHOTO_UPDATED,
    PHOTO_DELETED,
    PHOTO_CREATION_STOPPED,
    PHOTO_DELETION_STOPPED
}
